サインアップ機能
shinonome-inc/backend-final-assigment-Sasha pull request #1
Opened 2024-05-17 04:29 UTC by quinn-sasha

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-05-20 12:29 UTC, kotasuzuki72 reviewed
最終課題テスト要件の「サインアップ」のNo.13にHomeViewのテストを行うように書かれていますが，こちらのプログラムは書きましたか？

2024-05-20 12:29 UTC, kotasuzuki72 commented on accounts/tests.py
> +        form = response.context["form"]
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
response.context["form"]からformエラーを確認できている点が良いと思います．

2024-05-20 12:51 UTC, quinn-sasha commented on accounts/tests.py
> +        form = response.context["form"]
コメントありがとうございます!

No.13のHomeViewテストは account/tests.py の197行目に書きました。

```
class TestHomeView(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username="testuser", password="testpassword")
        self.client.login(username="testuser", password="testpassword")

    def test_success_get(self):
        response = self.client.get(reverse("tweets:home"))
        self.assertEqual(response.status_code, 200)

```

2024-05-20 12:58 UTC, kotasuzuki72 commented on accounts/tests.py
> +        form = response.context["form"]
承知しました．
可能であれば，tweets/test.pyのファイルを作り，そちらに書くと良いと思います！

2024-05-20 12:59 UTC, kotasuzuki72 approved these changes
LGTM

2024-05-20 13:49 UTC, quinn-sasha commented on accounts/tests.py
> +        form = response.context["form"]
はい、そのように修正しました。
ありがとうございました。

2024-05-21 03:06 UTC, IzmYuta requested changes
全体的に非常によく書けていると思います！
特に、テスト処理の共通化は面白いと思いました！ 👍 
ただ、いくつか修正してほしい場所があるので確認お願いします🙇

2024-05-21 03:06 UTC, IzmYuta commented on accounts/forms.py
> +        fields = ("username", "email")
`fields`はタプル`()`ではなく、リスト`[]`で定義するのが一般的です。

2024-05-21 03:06 UTC, IzmYuta commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
共通の処理を関数としてまとめている点は素晴らしいと思います。
ただ、1つの関数に複数の役割を持たせていて、関数名から想像できる処理と異なっている点が、個人的にわかりづらいと感じました。
「フォームエラーの確認」という名前に対して、「レスポンスの取得・検証」、「ユーザー登録の確認」も含まれていているのは、やや好ましくないです。
また、使い回しやすさという観点からも、役割を複数持たせない方が良いと考えます。
例えば、ユーザー登録の確認を分離すれば、117~124行目の処理も共通化できます。

2024-05-21 03:06 UTC, IzmYuta commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
また、test関数の中に埋もれていて、この関数がtest関数ではなく、共通処理関数であることがわかりづらいので、setUpの次あたりに置いておくと良いと思います。

2024-05-21 03:06 UTC, IzmYuta commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
今回は、複数フィールドをチェックする場合でもメッセージが共通なので、このような実装でも問題ないのですが、フィールドごとにメッセージが異なる場合はどうでしょうか？
フィールドごとに関数を呼び出してもいいのですが、スマートではないと思いませんか？
そこで、Dictを利用すると、フィールドとメッセージを1対1で対応づけることができ、よりスマートに実装できます。
ぜひ挑戦してみてください。

2024-05-21 03:06 UTC, IzmYuta commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
まとめると、
- ユーザー登録の確認処理を分離する
- レスポンス取得・検証処理を分離する、または関数名を変える
- 関数の定義場所をsetUp関数の次あたりに移動させる
- (余裕があれば)Dictを利用してよりスマートに実装する

2024-05-21 03:06 UTC, IzmYuta commented on tweets/views.py
> +    redirect_field_name = "next"  # ログイン後ホームページにリダイレクトされるようにする
redirect_field_nameを設定する際に、参考にしたページなどはありますか？

2024-05-21 08:47 UTC, quinn-sasha commented on accounts/forms.py
> +        fields = ("username", "email")
了解です
修正しました！

2024-05-22 00:12 UTC, quinn-sasha commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
修正しました。
最後のDictの利用は、少し難しかったです。

2024-05-22 00:13 UTC, quinn-sasha commented on tweets/views.py
> +    redirect_field_name = "next"  # ログイン後ホームページにリダイレクトされるようにする
申し訳ないですが、覚えてません。
思い出したら報告します。

2024-05-22 00:33 UTC, IzmYuta commented on accounts/tests.py
> +            self.assertIn(error_message, form.errors[field])
💯

2024-05-22 00:34 UTC, IzmYuta approved these changes
LGTM

2024-05-22 00:34 UTC, merged