フォロー機能
shinonome-inc/backend-final-assigment-Sasha pull request #4
Opened 2024-05-28 09:22 UTC by quinn-sasha

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-06-03 13:42 UTC, morita-y9 requested changes
非常に丁寧に書けていると思います！いくつか修正してほしい点があるのでお願いします！

2024-06-03 13:42 UTC, morita-y9 commented on accounts/views.py
例外処理も丁寧でとても良いと思います！

2024-06-03 13:42 UTC, morita-y9 commented on templates/accounts/follower_list.html
> +
following_listの方では，"フォローしているユーザー"と表示するようになっているので，こちらも文言を付け加えておくといいと思います．(変更は任意です)

2024-06-03 13:42 UTC, morita-y9 commented on accounts/models.py
> +        unique_together = ("follower", "followed")  # 絶対にfollowerとfollowedは等しくなる
unique_togetherは公式ドキュメント的には非推奨なのでUniqueConstraintを使う方が好ましいようです
参考https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together

2024-06-03 13:42 UTC, morita-y9 commented on accounts/views.py
> +        return Follow.objects.filter(follower=profile_user)
N+1問題が発生してしまっているようなので，修正してほしいです

2024-06-03 13:42 UTC, morita-y9 commented on accounts/views.py
> +        return Follow.objects.filter(followed=profile_user)
こちらのN+1問題もお願いします

2024-06-03 23:52 UTC, quinn-sasha commented on templates/accounts/follower_list.html
> +
確かにそうですね。タイトルが片方抜けていました。

2024-06-04 00:04 UTC, quinn-sasha commented on accounts/models.py
> +        unique_together = ("follower", "followed")  # 絶対にfollowerとfollowedは等しくなる
上記の方法で書き直しました。

2024-06-04 02:00 UTC, quinn-sasha commented on accounts/views.py
> +        return Follow.objects.filter(follower=profile_user)
原因は、Followインスタンスを取得する際にfollowed(ユーザー)を同時に取得していないことにあると考えられます。
フォローリストのtemplateで{{ follow.followed }}としているので、ここでユーザーを取得するクエリを発行しています。

しかしfollowリストを見る前にどこかで同じユーザーを取得するクエリを発行していた場合、n+1問題が発生します。

<修正案>
140行目: `return Follow.objects.filter(follower=profile_user).select_related("followed")`

自分で試してみましたが、問題は発生しなくなりました。

2024-06-04 02:00 UTC, quinn-sasha commented on accounts/models.py
> +        unique_together = ("follower", "followed")  # 絶対にfollowerとfollowedは等しくなる
UniqueConstraintで書き直しました。

2024-06-04 02:00 UTC, quinn-sasha commented on accounts/views.py
> +        return Follow.objects.filter(followed=profile_user)
FollowingListViewと同じような原因です。

2024-06-04 02:53 UTC, morita-y9 approved these changes

2024-06-05 14:44 UTC, HasegawaKota approved these changes

2024-06-05 14:44 UTC, merged

2024-06-05 14:47 UTC, HasegawaKota commented on templates/accounts/user_profile.html
> +                <input type="submit" value="フォロー">
強いて言えば自分自身のプロフィールを閲覧している時にフォローボタンを出さないよう実装してみても良いかもです！訂正は任意ですので次の課題に進んでかまいません！