いいね機能
shinonome-inc/backend-final-assigment-Sasha pull request #5
Opened 2024-06-06 03:05 UTC by quinn-sasha

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-06-06 14:10 UTC, kou1205 commented
いいねを押した後リロードすると取り消しにならずいいねに戻ってしまっているので修正お願いします。

2024-06-06 14:32 UTC, kou1205 commented
あとbase.htmlの<li><a href=" {% url 'welcome:welcome' %}">Twitter Clone</a></li>これはあまり動かした時に使われてないように感じたので残している理由がなければ消したほうがいいです！

2024-06-07 00:12 UTC, quinn-sasha commented
> あとbase.htmlの
> 
> * Twitter Clone
> これはあまり動かした時に使われてないように感じたので残している理由がなければ消したほうがいいです！

管理画面を見るときに使用することもありましたが、確かにwebアプリケーションとしては不要であることに同意です。
消去します。

2024-06-07 05:29 UTC, quinn-sasha commented
> いいねを押した後リロードすると取り消しにならずいいねに戻ってしまっているので修正お願いします。

コメントありがとうございます。

自分でいろいろ試してみたのですが、やはりリロードするといいねボタンのテキストが'like'になってしまいます。
おそらく問題は、サーバーからGETした情報が反映され、htmlでの条件分岐が再度リセットされているからです。
しかしviewクラスでどこが間違っているか特定できていない状態です。

もしよければヒントをいただけると助かります...

2024-06-08 14:39 UTC, kou1205 commented
> > いいねを押した後リロードすると取り消しにならずいいねに戻ってしまっているので修正お願いします。
> 
> コメントありがとうございます。
> 
> 自分でいろいろ試してみたのですが、やはりリロードするといいねボタンのテキストが'like'になってしまいます。 おそらく問題は、サーバーからGETした情報が反映され、htmlでの条件分岐が再度リセットされているからです。 しかしviewクラスでどこが間違っているか特定できていない状態です。
> 
> もしよければヒントをいただけると助かります...

すみません、色々自分でも検討してみていますがビューじゃなさそうですね、、、JSの問題な感じがしますね。JSを修正しても治らなければもう一度聞いてもらってもいいですか？

2024-06-08 23:47 UTC, quinn-sasha commented
> > > いいねを押した後リロードすると取り消しにならずいいねに戻ってしまっているので修正お願いします。
> > 
> > 
> > コメントありがとうございます。
> > 自分でいろいろ試してみたのですが、やはりリロードするといいねボタンのテキストが'like'になってしまいます。 おそらく問題は、サーバーからGETした情報が反映され、htmlでの条件分岐が再度リセットされているからです。 しかしviewクラスでどこが間違っているか特定できていない状態です。
> > もしよければヒントをいただけると助かります...
> 
> すみません、色々自分でも検討してみていますがビューじゃなさそうですね、、、JSの問題な感じがしますね。JSを修正しても治らなければもう一度聞いてもらってもいいですか？

返信ありがとうございます。
JSは前回のコミット時に修正したつもりだったのですが、まだ不完全な様ですね。
特にJSに対する理解が浅いので、なぜ間違っているのかがわからないため行き詰まっています。

2024-06-10 12:37 UTC, kou1205 commented
いいねの問題も解決していてグッとみやすくなったと思います！

2024-06-10 12:45 UTC, kou1205 commented
細かい部分なのですがbase.htmlのbootstrapのバージョンが４なので５に変更してください。

2024-06-11 02:31 UTC, quinn-sasha commented
> base.htmlのbootstrapのバージョンが４なので５に変更してください。細かくてすみません！

了解です。変更しました！

2024-06-11 02:33 UTC, kou1205 commented
OKです！

2024-06-17 13:40 UTC, IzmYuta requested changes
非常によく書けています！
数点直してもらいたいところがあるので確認お願いします！

2024-06-17 13:40 UTC, IzmYuta commented on tweets/migrations/0002_like.py
まだmergeされていない状態であれば、マイグレーションファイルは1つにまとめてしまっても大丈夫です。
0002_like.py以降のマイグレーションファイルを削除し、改めてマイグレーションファイルの作成を行ってください。

2024-06-17 13:40 UTC, IzmYuta commented on tweets/migrations/0002_like.py
注意点として、マイグレーションファイルを作り直した場合、DBも作り直す必要があります。
mergeされていない状態であれば、ローカル(自分のPC)上のDBを作り直すだけで済むので問題ありません。

すでにmergeされたものに対して行うと、他の開発者にDBの再作成をお願いする必要があるだけでなく、すでに運用されているアプリケーションに影響を与えてクライアントに頭を下げる必要があるため、注意しましょう(体験談)

2024-06-17 13:40 UTC, IzmYuta commented on tweets/models.py
> +    # likeとtweet, userのモデル間関係は'one-to-many'
いいねを中心とすると、図のようなone-to-manyが2つ組み合わさった関係になります。
イメージ通りであればOKです。

<img width="300" alt="2B59F9C1-E256-41C3-9021-76C00FD3781D" src="https://github.com/shinonome-inc/backend-final-assigment-Sasha/assets/104307371/07b653d8-7e67-4dd6-8c32-922fc6d08d01">

2024-06-17 13:40 UTC, IzmYuta commented on tweets/models.py
> +    # likeとtweet, userのモデル間関係は'one-to-many'
ちなみに、userとtweetに着目するとmany-to-manyの関係になります。
many-to-manyをストレートに実装しようとすると結構難しかったりします。
今回は、likeという中間テーブルを置いてone-to-many2つでmany-to-manyを表現しています。

このような、中間テーブルを用いてmany-to-manyを表現する手法はよく用いるので覚えておきましょう。

2024-06-17 13:40 UTC, IzmYuta commented on tweets/tests.py
> +        self.assertEqual(Like.objects.all().count(), 0)  # DBから削除完了
存在するか否かをチェックするだけならexistsメソッドを使うようにしましょう。
テストデータの件数が小さい場合は正直countでもいいのですが、癖付けとして意識しておきましょう。

[参考](https://ameblo.jp/archive-redo-blog/entry-10035200905.html)

2024-06-17 22:17 UTC, quinn-sasha commented on tweets/migrations/0002_like.py
気おつけます

2024-06-17 22:18 UTC, quinn-sasha commented on tweets/models.py
> +    # likeとtweet, userのモデル間関係は'one-to-many'
図表のおかげでわかりやすいです
理解できました

2024-06-18 08:48 UTC, IzmYuta commented on tweets/views.py
> +@method_decorator(login_required, name="dispatch")
ここでLoginRequiredMixinではなく、@method_decorator(login_required, name="dispatch")とした理由はありますか？

2024-06-18 09:20 UTC, quinn-sasha commented on tweets/views.py
> +@method_decorator(login_required, name="dispatch")
Viewクラスを利用したので、LoginRequiredMixinがViewで使用できなかったからです。おそらく。

2024-06-18 09:45 UTC, IzmYuta commented on tweets/views.py
> +@method_decorator(login_required, name="dispatch")
Viewクラスでも利用可能です。[参考](https://docs.djangoproject.com/en/5.0/topics/auth/default/#the-loginrequiredmixin-mixin)
やっていること自体はLoginRequiredMixinでも@method_decorator(login_required, name="dispatch")でも変わらなそうなので修正はお任せします。

2024-06-18 09:45 UTC, IzmYuta approved these changes
LGTM

2024-06-18 10:55 UTC, merged